// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smvspuwtsmlbnmjguawy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdnNwdXd0c21sYm5tamd1YXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI5NTQsImV4cCI6MjA2NTQ5ODk1NH0.HGIamrAWUVsIBBv_gZyoGlSAtP8gsS0m6OLMmRHwgso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);